#debug = true

logLevel = "WARN" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC
InsecureSkipVerify = true 
defaultEntryPoints = ["https", "http"]

# WEB interface of Traefik - it will show web page with overview of frontend and backend configurations 
[api]
  entryPoint = "traefik"
  dashboard = true
  address = ":8080"
  usersFile = "/shared/.htpasswd"

# Force HTTPS
[entryPoints]
 [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
 [entryPoints.https]
 address = ":443"

 [entryPoints.https.tls]


[ping]


# Let's encrypt configuration
[acme]
email = "salviof@gmail.com" #any email id will work
storage="/etc/traefik/acme/acme.json"
entryPoint = "https"
acmeLogging=true 
onDemand = false #create certificate when container is created
onHostRule = true

[acme.httpChallenge]
  entryPoint = "http"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "nuvem.casanovadigital.com.br"
watch = true
# This will hide all docker containers that don't have explicitly  
# set label to "enable"
exposedbydefault = false

 [file]
  watch = true
  directory = "/etc/traefik/site"
